### ISSUE TITLE
Inject success but nothing happened?

### ISSUE THREAD

**Issue by AraragiHoozuki** [super-continent/gbvs-hook#1]
Does this need any update?

**Comment by super-continent** [comment]
Did GBVS recieve an update? I dont see anything past june 8th

**Comment by super-continent** [comment]
Just opened the game with a debugger, cant seem to see any difference in the function that runs, also I injected the DLL myself and it works fine, loads the mods normally

**Comment by AraragiHoozuki** [comment]
> Just opened the game with a debugger, cant seem to see any difference in the function that runs, also I injected the DLL myself and it works fine, loads the mods normally

so strange, the commandline tells me injection success but no window is shown..

**Comment by super-continent** [comment]
Try building with the AllocConsole() call uncommented, it should bring up a window that outputs a log of actions, it might tell you more info

**Comment by AraragiHoozuki** [comment]
> Try building with the AllocConsole() call uncommented, it should bring up a window that outputs a log of actions, it might tell you more info
output log is like this:
```
Injected! Initializing...
Got base address: 0x0
LoadScript function address is 0x4CD120
Creating GUI...
Created GUI!
Creating hook...
thread '<unnamed>' panicked at 'Could not initialize hook!: RegionFailure(FreeMemory)', src\lib.rs:145:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Looks like that base address was wrong?

**Comment by super-continent** [comment]
Huh, looks like in this case it got a null pointer as the base address from GetModuleHandleA(NULL) (which normally returns the base addr of the main executable if you give it NULL as the argument) so it wouldve tried to access unallocatedallocated memory

**Comment by super-continent** [comment]
Actually I'm not passing NULL in the argument, I'm passing the name of the EXE, does GBVS have the same exe name on your pc? it could be an error where it just doesnt pass the right argument, i might be able to just pass NULL instead

**Comment by super-continent** [comment]
Just changed the code to pass NULL to GetModuleHandleA() instead, might work now, try building and see if you still get the error @AraragiHoozuki

**Comment by AraragiHoozuki** [comment]
@super-continent  Thanks a lot! I tried to pass NULL as arg and it works fine!
 BTW, if I pass the proccess name it won't find the correct address (I copy and paste the exe name so it should be right ), it's weird... nevertheless now it works.
